### ISSUE TITLE
Wrong bitshift operation in WeightedRendezvousStrategy

### ISSUE THREAD

**Issue by PtD** [ykayacan/hashing-utils#18]
Instead of  
private static final long FTO = (0xFF_FF_FF_FF_FF_FF_FF_FFL >> (64 - 53));
it should be
 private static final long FTO = (0xFF_FF_FF_FF_FF_FF_FF_FFL >>> (64 - 53));

Otherwise the shift operation can yield a result that is bigger than FTZ

**Comment by ilhan-mstf** [comment]
I would like to work on this issue.
